[gcloud]
format = 'on [$symbol$account(@$domain)(\($project\))]($style) '

[docker_context]
format = "via [ğŸ‹ $context](blue bold)"

[memory_usage]
disabled = false
threshold = -1
symbol = " "
style = "bold dimmed green"

[rust]
format = "via [âš™ï¸ $version](red bold)"

[java]
symbol = "ğŸŒŸ "
